// Generated by CoffeeScript 1.6.2
var colours, main, offset, svg_height, svg_width, _drawCircles, _drawLine;

svg_width = window.innerWidth;

svg_height = window.innerHeight;

offset = 0.01;

colours = ['teal', 'silver', 'sienna', 'plum', 'orange', 'indigo', 'gold', 'cyan', 'red', 'aqua'];

_drawCircles = function(nodes, SVG) {
  var circleAttributes, circles, text, textAttributes;

  console.log(nodes);
  circles = SVG.selectAll("circle").data(nodes).enter().append("circle").style("fill", "white").style("stroke", "black").style("stroke-width", 4);
  circleAttributes = circles.attr("cx", function(d) {
    return d.x * svg_width;
  }).attr("cy", function(d) {
    return d.y * svg_height;
  }).attr("r", 7);
  text = SVG.selectAll('text').data(nodes).enter().append('text').style('font-family', 'sans-serif').style('font-size', 16).style('fill', 'gray');
  return textAttributes = text.attr("x", function(d) {
    return (d.x + offset) * svg_width;
  }).attr("y", function(d) {
    return (d.y + offset) * svg_height;
  }).text(function(d) {
    return d.label;
  });
};

_drawLine = function(nodes, path, colour, SVG, animate) {
  var lineFunction, lineGraph, totalLength;

  lineFunction = d3.svg.line().x(function(d) {
    return nodes[d].x * svg_width;
  }).y(function(d) {
    return nodes[d].y * svg_height;
  }).interpolate("cardinal");
  lineGraph = SVG.append("path").attr("d", lineFunction(path.nodes)).attr("stroke", colour).attr("stroke-width", 5).attr("fill", "none").attr("fill", "none").attr('opacity', '0.6');
  if (animate) {
    totalLength = lineGraph.node().getTotalLength();
    return lineGraph.attr("stroke-dasharray", totalLength + " " + totalLength).attr("stroke-dashoffset", totalLength).transition().duration(10000).ease("linear").attr("stroke-dashoffset", 0);
  } else {
    totalLength = lineGraph.node().getTotalLength();
    return lineGraph.attr("stroke-dasharray", totalLength + " " + totalLength).attr("stroke-dashoffset", totalLength).transition().duration(0).ease("linear").attr("stroke-dashoffset", 0);
  }
};

main = function(data, animate) {
  var i, path, svg, _i, _len, _ref, _results;

  svg = d3.select(".span12").append("svg").attr("width", svg_width).attr("height", svg_height);
  _drawCircles(data.nodes, svg);
  _ref = data.paths;
  _results = [];
  for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
    path = _ref[i];
    _results.push(_drawLine(data.nodes, path, colours[i], svg, animate));
  }
  return _results;
};
